// Each template: id, name, slot, style, prepTime/cookTime (minutes),
// items [{food, grams}], instructions (array of steps).
// Grams are BASE amounts for one serving before the planner scales them to hit calorie targets.
// style is a small preparation-format tag (reused across slots) used, alongside each item's
// proteinFamily in foods.js, to bias meal selection toward a person's stated preferences.
const MEAL_TEMPLATES = [
  // ---------- BREAKFAST ----------
  { id: "b1", slot: "breakfast", style: "oats", name: "Oatmeal with Banana & Peanut Butter", prepTime: 3, cookTime: 5,
    items: [{ food: "oats", grams: 60 }, { food: "almond_milk", grams: 200 }, { food: "banana", grams: 120 }, { food: "peanut_butter", grams: 16 }],
    instructions: ["Combine the oats and almond milk in a small pot.", "Bring to a gentle simmer over medium heat, stirring occasionally, until thickened, about 4-5 minutes.", "Remove from heat. Slice the banana and stir half the slices in.", "Spoon into a bowl, top with the remaining banana and a drizzle of peanut butter."] },
  { id: "b2", slot: "breakfast", style: "dairy_bowl", name: "Greek Yogurt Parfait", prepTime: 5, cookTime: 0,
    items: [{ food: "greek_yogurt", grams: 200 }, { food: "granola", grams: 40 }, { food: "blueberries", grams: 80 }],
    instructions: ["Spoon a layer of Greek yogurt into a bowl or jar.", "Add a layer of granola, then a layer of blueberries.", "Repeat the layers once more if using a tall glass.", "Serve immediately so the granola stays crunchy."] },
  { id: "b3", slot: "breakfast", style: "eggs", name: "Veggie Egg Scramble with Toast", prepTime: 5, cookTime: 7,
    items: [{ food: "egg", grams: 150 }, { food: "spinach", grams: 40 }, { food: "bell_pepper", grams: 50 }, { food: "whole_wheat_bread", grams: 70 }],
    instructions: ["Crack the eggs into a bowl and whisk until no streaks of white remain.", "Heat a lightly oiled pan over medium heat. Pour in the eggs and let sit undisturbed 20 seconds, then gently push and fold with a spatula.", "Add the chopped spinach and diced bell pepper during the last 2 minutes, folding until the eggs are just set and the spinach has wilted.", "Toast the bread until golden and serve alongside."] },
  { id: "b4", slot: "breakfast", style: "eggs", name: "Avocado Toast with Egg", prepTime: 5, cookTime: 5,
    items: [{ food: "whole_wheat_bread", grams: 70 }, { food: "avocado", grams: 75 }, { food: "egg", grams: 50 }],
    instructions: ["Toast the bread until crisp and golden.", "Mash the avocado in a small bowl with a pinch of salt and pepper until mostly smooth.", "Spread the mashed avocado evenly over the toast.", "Fry or poach the egg to your liking (about 3 minutes for a runny yolk) and place on top."] },
  { id: "b5", slot: "breakfast", style: "dairy_bowl", name: "Cottage Cheese & Fruit Bowl", prepTime: 5, cookTime: 0,
    items: [{ food: "cottage_cheese", grams: 200 }, { food: "apple", grams: 120 }, { food: "almonds", grams: 15 }],
    instructions: ["Dice the apple into bite-sized pieces.", "Spoon the cottage cheese into a bowl.", "Top with the diced apple and almonds.", "Finish with a dash of cinnamon if you like."] },
  { id: "b6", slot: "breakfast", style: "eggs", name: "Eggs, Bacon & Toast", prepTime: 3, cookTime: 10,
    items: [{ food: "egg", grams: 120 }, { food: "bacon", grams: 40 }, { food: "whole_wheat_bread", grams: 70 }],
    instructions: ["Cook the bacon in a pan over medium heat, turning occasionally, until crisp, about 6-8 minutes.", "Transfer the bacon to a paper-towel-lined plate; keep a spoonful of the rendered fat in the pan.", "Crack the eggs into the pan and fry or scramble to your liking, 2-3 minutes.", "Toast the bread and serve everything together."] },
  { id: "b7", slot: "breakfast", style: "eggs", name: "Egg & Sausage Scramble with Toast", prepTime: 5, cookTime: 8,
    items: [{ food: "egg", grams: 120 }, { food: "breakfast_sausage", grams: 60 }, { food: "whole_wheat_bread", grams: 70 }, { food: "bell_pepper", grams: 40 }],
    instructions: ["Brown the breakfast sausage in a pan over medium heat, breaking it up with a spatula as it cooks, 4-5 minutes.", "Whisk the eggs in a bowl.", "Pour the eggs and diced bell pepper into the pan with the sausage; scramble gently until just set, 2-3 minutes.", "Toast the bread and serve alongside."] },
  { id: "b8", slot: "breakfast", style: "eggs", name: "Breakfast Burrito", prepTime: 5, cookTime: 7,
    items: [{ food: "egg", grams: 120 }, { food: "cheddar_cheese", grams: 30 }, { food: "tortilla", grams: 60 }, { food: "bell_pepper", grams: 40 }],
    instructions: ["Whisk the eggs in a bowl.", "Scramble the eggs with the diced bell pepper in a lightly oiled pan over medium heat until just set, about 3 minutes.", "Warm the tortilla in a dry pan or microwave for 15-20 seconds until pliable.", "Fill the tortilla with the scrambled eggs, top with shredded cheddar, then fold in the sides and roll up."] },
  { id: "b9", slot: "breakfast", style: "eggs", name: "Turkey & Egg Power Scramble", prepTime: 5, cookTime: 8,
    items: [{ food: "turkey_breast", grams: 90 }, { food: "egg", grams: 100 }, { food: "whole_wheat_bread", grams: 40 }, { food: "spinach", grams: 40 }],
    instructions: ["Dice the turkey breast into small cubes.", "Sear in a lightly oiled pan over medium heat until browned and cooked through, about 5 minutes.", "Whisk the eggs and pour into the pan with the spinach.", "Scramble gently until the eggs are just set and the spinach has wilted, 2-3 minutes.", "Serve with a slice of toast on the side."] },
  { id: "b10", slot: "breakfast", style: "eggs", name: "Savory Chicken Breakfast Skillet", prepTime: 5, cookTime: 9,
    items: [{ food: "chicken_breast", grams: 100 }, { food: "egg", grams: 80 }, { food: "bell_pepper", grams: 60 }],
    instructions: ["Dice the chicken breast into bite-sized pieces and season with salt and pepper.", "Pan-sear over medium heat until cooked through, about 6-7 minutes.", "Push the chicken to one side of the pan; whisk the eggs and pour into the empty side with the diced bell pepper.", "Scramble the eggs until just set, then combine everything and serve hot."] },
  { id: "b11", slot: "breakfast", style: "oats", name: "Apple Cinnamon Oatmeal", prepTime: 3, cookTime: 5,
    items: [{ food: "oats", grams: 60 }, { food: "almond_milk", grams: 200 }, { food: "apple", grams: 100 }, { food: "almonds", grams: 15 }],
    instructions: ["Combine the oats and almond milk in a small pot.", "Simmer over medium heat, stirring occasionally, until thickened, about 4-5 minutes.", "Dice the apple; stir most of it into the oatmeal, saving a few pieces for the top.", "Spoon into a bowl and top with the remaining apple, almonds, and a dash of cinnamon."] },
  { id: "b12", slot: "breakfast", style: "oats", name: "Protein Overnight Oats", prepTime: 5, cookTime: 0,
    items: [{ food: "oats", grams: 50 }, { food: "greek_yogurt", grams: 150 }, { food: "peanut_butter", grams: 16 }, { food: "banana", grams: 100 }],
    instructions: ["Stir the oats, Greek yogurt, and peanut butter together in a jar until well combined.", "Cover and refrigerate overnight (or at least 2 hours) until the oats have softened.", "Slice the banana and top just before eating."] },
  { id: "b13", slot: "breakfast", style: "dairy_bowl", name: "Cottage Cheese Berry Bowl", prepTime: 3, cookTime: 0,
    items: [{ food: "cottage_cheese", grams: 200 }, { food: "blueberries", grams: 70 }, { food: "granola", grams: 25 }],
    instructions: ["Spoon the cottage cheese into a bowl.", "Top with the blueberries and a sprinkle of granola for crunch.", "Serve chilled."] },
  { id: "b14", slot: "breakfast", style: "oats", name: "Berry Overnight Oats", prepTime: 5, cookTime: 0,
    items: [{ food: "oats", grams: 50 }, { food: "almond_milk", grams: 180 }, { food: "blueberries", grams: 60 }, { food: "almonds", grams: 15 }],
    instructions: ["Stir the oats and almond milk together in a jar.", "Cover and refrigerate overnight, or at least 2 hours, until softened.", "Top with blueberries and almonds before eating."] },

  // ---------- LUNCH ----------
  { id: "l1", slot: "lunch", style: "bowl", name: "Chicken & Rice Bowl", prepTime: 5, cookTime: 15,
    items: [{ food: "chicken_breast", grams: 150 }, { food: "brown_rice", grams: 200 }, { food: "broccoli", grams: 100 }, { food: "olive_oil", grams: 5 }],
    instructions: ["Season the chicken breast with salt and pepper.", "Pan-sear or bake until cooked through (internal temperature 165°F), about 12-14 minutes.", "Meanwhile, steam the broccoli until bright green and tender-crisp, 4-5 minutes.", "Slice the chicken and serve over rice with the broccoli, drizzled with olive oil."] },
  { id: "l2", slot: "lunch", style: "wrap_sandwich", name: "Turkey & Hummus Wrap Plate", prepTime: 5, cookTime: 0,
    items: [{ food: "turkey_breast", grams: 100 }, { food: "whole_wheat_bread", grams: 70 }, { food: "hummus", grams: 40 }, { food: "carrots", grams: 60 }],
    instructions: ["Spread the hummus evenly over the bread.", "Layer the sliced turkey breast on top.", "Fold or roll up the bread.", "Serve with carrot sticks on the side."] },
  { id: "l3", slot: "lunch", style: "salad", name: "Quinoa Black Bean Salad", prepTime: 8, cookTime: 0,
    items: [{ food: "quinoa", grams: 150 }, { food: "black_beans", grams: 120 }, { food: "bell_pepper", grams: 60 }, { food: "avocado", grams: 50 }, { food: "olive_oil", grams: 5 }],
    instructions: ["Combine the cooked quinoa and black beans in a bowl.", "Dice the bell pepper and add it in.", "Slice the avocado and arrange on top.", "Drizzle with olive oil (and a squeeze of lime if you have one), toss gently, and serve."] },
  { id: "l4", slot: "lunch", style: "stir_fry", name: "Tofu Veggie Stir Fry", prepTime: 8, cookTime: 9,
    items: [{ food: "tofu", grams: 150 }, { food: "brown_rice", grams: 150 }, { food: "broccoli", grams: 100 }, { food: "bell_pepper", grams: 60 }, { food: "olive_oil", grams: 8 }, { food: "soy_sauce", grams: 12 }],
    instructions: ["Press the tofu between paper towels for a few minutes to remove excess moisture, then cube it.", "Pan-fry in olive oil over medium-high heat until golden on most sides, about 5 minutes.", "Add the broccoli and bell pepper; stir-fry until tender-crisp, 4-5 minutes.", "Stir in the soy sauce during the last minute, tossing to coat, then serve over brown rice."] },
  { id: "l5", slot: "lunch", style: "soup", name: "Lentil Soup with Bread", prepTime: 5, cookTime: 12,
    items: [{ food: "lentils", grams: 250 }, { food: "carrots", grams: 60 }, { food: "whole_wheat_bread", grams: 50 }],
    instructions: ["Dice the carrots.", "Combine the cooked lentils, carrots, and a splash of broth or water in a pot.", "Simmer over medium heat until the carrots are tender, about 10 minutes.", "Season with cumin, salt, and pepper; serve hot with a side of bread."] },
  { id: "l6", slot: "lunch", style: "bowl", name: "Salmon Spinach Quinoa Bowl", prepTime: 5, cookTime: 12,
    items: [{ food: "salmon", grams: 120 }, { food: "spinach", grams: 60 }, { food: "quinoa", grams: 100 }, { food: "olive_oil", grams: 5 }],
    instructions: ["Season the salmon with salt and pepper.", "Pan-sear or bake until it flakes easily with a fork, about 10-12 minutes.", "In the last couple minutes, wilt the spinach in a separate warm pan.", "Serve the salmon over quinoa and spinach, drizzled with olive oil."] },
  { id: "l7", slot: "lunch", style: "wrap_sandwich", name: "Turkey & Cheese Sandwich", prepTime: 5, cookTime: 0,
    items: [{ food: "turkey_breast", grams: 90 }, { food: "whole_wheat_bread", grams: 70 }, { food: "cheddar_cheese", grams: 25 }, { food: "carrots", grams: 60 }],
    instructions: ["Layer the sliced turkey and cheddar between the bread slices.", "Cut the sandwich in half.", "Serve with carrot sticks on the side."] },
  { id: "l8", slot: "lunch", style: "wrap_sandwich", name: "Grilled Cheese & Apple", prepTime: 5, cookTime: 6,
    items: [{ food: "whole_wheat_bread", grams: 70 }, { food: "cheddar_cheese", grams: 40 }, { food: "olive_oil", grams: 5 }, { food: "apple", grams: 120 }],
    instructions: ["Layer the cheddar between the bread slices.", "Heat the olive oil in a pan over medium heat.", "Pan-fry the sandwich, a few minutes per side, pressing gently, until golden and the cheese has melted.", "Slice and serve with the apple on the side."] },
  { id: "l9", slot: "lunch", style: "salad", name: "Grilled Chicken Caesar Salad", prepTime: 5, cookTime: 10,
    items: [{ food: "chicken_breast", grams: 130 }, { food: "spinach", grams: 100 }, { food: "parmesan_cheese", grams: 20 }, { food: "caesar_dressing", grams: 20 }],
    instructions: ["Season the chicken breast with salt and pepper.", "Grill or pan-sear until cooked through, about 6-7 minutes per side, then slice.", "Toss the spinach with the Caesar dressing in a bowl until evenly coated.", "Top with the sliced chicken and shaved parmesan."] },
  { id: "l10", slot: "lunch", style: "stir_fry", name: "Chicken Veggie Stir Fry", prepTime: 8, cookTime: 9,
    items: [{ food: "chicken_breast", grams: 130 }, { food: "brown_rice", grams: 150 }, { food: "broccoli", grams: 100 }, { food: "bell_pepper", grams: 60 }, { food: "olive_oil", grams: 8 }, { food: "soy_sauce", grams: 12 }],
    instructions: ["Cut the chicken breast into thin strips.", "Stir-fry in olive oil over medium-high heat until cooked through, about 5 minutes.", "Add the broccoli and bell pepper; stir-fry until tender-crisp, 4-5 minutes.", "Stir in the soy sauce during the last minute, tossing to coat, then serve over brown rice."] },
  { id: "l11", slot: "lunch", style: "soup", name: "Chicken Noodle Soup", prepTime: 5, cookTime: 13,
    items: [{ food: "chicken_breast", grams: 100 }, { food: "pasta", grams: 150 }, { food: "carrots", grams: 60 }, { food: "spinach", grams: 40 }],
    instructions: ["Dice the chicken breast.", "Simmer the chicken with broth and the diced carrots in a pot for about 10 minutes, until the chicken is cooked through.", "Add the cooked pasta and spinach; simmer 2-3 more minutes until the spinach wilts.", "Season with salt and pepper and serve hot."] },
  { id: "l12", slot: "lunch", style: "wrap_sandwich", name: "Tuna Salad Sandwich", prepTime: 6, cookTime: 0,
    items: [{ food: "tuna", grams: 100 }, { food: "whole_wheat_bread", grams: 70 }, { food: "avocado", grams: 40 }, { food: "carrots", grams: 50 }],
    instructions: ["Drain the tuna and place in a bowl.", "Mash the avocado into the tuna with a fork until creamy.", "Spread the mixture between the bread slices.", "Serve with carrot sticks on the side."] },
  { id: "l13", slot: "lunch", style: "bowl", name: "Turkey Quinoa Bowl", prepTime: 5, cookTime: 8,
    items: [{ food: "turkey_breast", grams: 120 }, { food: "quinoa", grams: 150 }, { food: "broccoli", grams: 100 }, { food: "olive_oil", grams: 5 }],
    instructions: ["Dice the turkey breast and season with salt and pepper.", "Pan-sear over medium heat until cooked through, about 6-7 minutes.", "Steam the broccoli until tender-crisp, 4-5 minutes.", "Serve the turkey and broccoli over quinoa, drizzled with olive oil."] },
  { id: "l14", slot: "lunch", style: "stir_fry", name: "Beef Veggie Stir Fry", prepTime: 5, cookTime: 12,
    items: [{ food: "ground_beef", grams: 120 }, { food: "brown_rice", grams: 180 }, { food: "bell_pepper", grams: 80 }, { food: "broccoli", grams: 80 }, { food: "soy_sauce", grams: 12 }],
    instructions: ["Brown the ground beef in a pan over medium-high heat, breaking it up, until fully cooked, about 6-7 minutes.", "Add the bell pepper and broccoli; stir-fry until tender-crisp, about 5 minutes.", "Stir in the soy sauce during the last minute, tossing to coat, then serve over brown rice."] },
  { id: "l15", slot: "lunch", style: "soup", name: "Turkey Vegetable Soup", prepTime: 5, cookTime: 13,
    items: [{ food: "turkey_breast", grams: 100 }, { food: "carrots", grams: 60 }, { food: "spinach", grams: 40 }, { food: "pasta", grams: 100 }],
    instructions: ["Dice the turkey breast.", "Simmer the turkey with broth and the diced carrots in a pot for about 10 minutes, until cooked through.", "Add the cooked pasta and spinach; simmer 2-3 more minutes until the spinach wilts.", "Season with salt and pepper and serve hot."] },
  { id: "l16", slot: "lunch", style: "salad", name: "Salmon Spinach Salad", prepTime: 5, cookTime: 10,
    items: [{ food: "salmon", grams: 120 }, { food: "spinach", grams: 100 }, { food: "carrots", grams: 50 }, { food: "olive_oil", grams: 5 }],
    instructions: ["Season the salmon with salt and pepper.", "Pan-sear or bake until it flakes easily, about 8-10 minutes.", "Toss the spinach and shredded carrots with olive oil.", "Top with the salmon and serve."] },
  { id: "l17", slot: "lunch", style: "wrap_sandwich", name: "Turkey Avocado Wrap", prepTime: 5, cookTime: 0,
    items: [{ food: "turkey_breast", grams: 100 }, { food: "tortilla", grams: 60 }, { food: "avocado", grams: 50 }, { food: "spinach", grams: 40 }],
    instructions: ["Mash the avocado with a pinch of salt and pepper.", "Spread the mashed avocado over the tortilla.", "Layer the turkey and spinach on top, then roll up tightly.", "Slice in half and serve."] },

  // ---------- DINNER ----------
  { id: "d1", slot: "dinner", style: "bowl", name: "Baked Salmon with Sweet Potato", prepTime: 8, cookTime: 25,
    items: [{ food: "salmon", grams: 150 }, { food: "sweet_potato", grams: 200 }, { food: "broccoli", grams: 100 }, { food: "olive_oil", grams: 5 }],
    instructions: ["Preheat the oven to 400°F.", "Cube the sweet potato, toss with olive oil, and spread on a baking sheet.", "Roast for 20-25 minutes, flipping halfway, until fork-tender.", "Season the salmon and add it to the oven for the last 12-15 minutes, until it flakes easily.", "Steam the broccoli in the last 5 minutes and plate everything together."] },
  { id: "d2", slot: "dinner", style: "stir_fry", name: "Lean Beef & Veggie Stir Fry", prepTime: 5, cookTime: 12,
    items: [{ food: "ground_beef", grams: 120 }, { food: "brown_rice", grams: 180 }, { food: "bell_pepper", grams: 80 }, { food: "broccoli", grams: 80 }, { food: "soy_sauce", grams: 12 }],
    instructions: ["Brown the ground beef in a pan over medium-high heat, breaking it up with a spatula, until fully cooked, about 6-7 minutes.", "Add the bell pepper and broccoli; stir-fry until tender-crisp, about 5 minutes.", "Stir in the soy sauce during the last minute, tossing to coat, then serve over brown rice."] },
  { id: "d3", slot: "dinner", style: "bowl", name: "Chicken Fajita Bowl", prepTime: 8, cookTime: 10,
    items: [{ food: "chicken_breast", grams: 150 }, { food: "bell_pepper", grams: 100 }, { food: "brown_rice", grams: 150 }, { food: "cheddar_cheese", grams: 20 }],
    instructions: ["Slice the chicken and bell peppers into thin strips.", "Season with fajita spices (chili powder, cumin, paprika).", "Sauté together in a hot pan over medium-high heat until the chicken is cooked through, 8-10 minutes.", "Serve over rice, topped with shredded cheddar."] },
  { id: "d4", slot: "dinner", style: "soup", name: "Turkey & Black Bean Chili", prepTime: 5, cookTime: 18,
    items: [{ food: "turkey_breast", grams: 120 }, { food: "black_beans", grams: 150 }, { food: "bell_pepper", grams: 60 }, { food: "cheddar_cheese", grams: 20 }],
    instructions: ["Cook the diced or ground turkey in a pot over medium heat until browned, about 5 minutes.", "Add the black beans, diced bell pepper, and chili spices.", "Simmer for 15 minutes, stirring occasionally, until the flavors come together.", "Top with shredded cheddar before serving."] },
  { id: "d5", slot: "dinner", style: "bowl", name: "Pasta with Tofu & Spinach", prepTime: 8, cookTime: 12,
    items: [{ food: "pasta", grams: 200 }, { food: "tofu", grams: 120 }, { food: "spinach", grams: 60 }, { food: "olive_oil", grams: 8 }],
    instructions: ["Cook the pasta according to package instructions; drain.", "Meanwhile, cube the tofu and pan-fry in olive oil over medium-high heat until golden, about 6-7 minutes.", "Add the spinach to the pan in the last minute, wilting it.", "Toss the tofu and spinach through the pasta and serve."] },
  { id: "d6", slot: "dinner", style: "bowl", name: "Sweet Potato & Black Bean Bowl", prepTime: 8, cookTime: 22,
    items: [{ food: "sweet_potato", grams: 200 }, { food: "black_beans", grams: 150 }, { food: "spinach", grams: 40 }, { food: "avocado", grams: 50 }],
    instructions: ["Preheat the oven to 400°F.", "Cube the sweet potato and roast for 20-25 minutes, until fork-tender.", "Warm the black beans in a small pot with a pinch of cumin.", "Assemble in a bowl over the spinach, topped with the roasted sweet potato and sliced avocado."] },
  { id: "d7", slot: "dinner", style: "bowl", name: "Chicken & Broccoli Pasta", prepTime: 8, cookTime: 12,
    items: [{ food: "pasta", grams: 200 }, { food: "chicken_breast", grams: 130 }, { food: "broccoli", grams: 100 }, { food: "olive_oil", grams: 8 }],
    instructions: ["Cook the pasta according to package instructions; drain.", "Meanwhile, pan-sear the chicken over medium heat until cooked through, about 7-8 minutes, then slice.", "Steam the broccoli until tender-crisp, 4-5 minutes.", "Toss the pasta, chicken, and broccoli together with the olive oil and serve."] },
  { id: "d8", slot: "dinner", style: "salad", name: "Grilled Chicken Salad", prepTime: 5, cookTime: 12,
    items: [{ food: "chicken_breast", grams: 150 }, { food: "spinach", grams: 120 }, { food: "avocado", grams: 60 }, { food: "olive_oil", grams: 8 }],
    instructions: ["Season the chicken breast with salt and pepper.", "Grill or pan-sear until cooked through, about 6-7 minutes per side, then slice.", "Toss the spinach with olive oil in a bowl.", "Top with the sliced chicken and avocado."] },
  { id: "d9", slot: "dinner", style: "wrap_sandwich", name: "Turkey Wrap Plate", prepTime: 5, cookTime: 1,
    items: [{ food: "turkey_breast", grams: 130 }, { food: "tortilla", grams: 60 }, { food: "cheddar_cheese", grams: 25 }, { food: "spinach", grams: 50 }],
    instructions: ["Warm the tortilla in a dry pan or microwave for 15-20 seconds until pliable.", "Layer the sliced turkey, cheddar, and spinach on top.", "Fold in the sides and roll up tightly.", "Slice in half and serve."] },
  { id: "d10", slot: "dinner", style: "soup", name: "Hearty Beef & Bean Soup", prepTime: 5, cookTime: 18,
    items: [{ food: "ground_beef", grams: 120 }, { food: "black_beans", grams: 150 }, { food: "carrots", grams: 70 }, { food: "bell_pepper", grams: 50 }],
    instructions: ["Brown the ground beef in a pot over medium heat, breaking it up as it cooks, about 5-6 minutes.", "Add the black beans, diced carrots, and bell pepper along with a splash of broth.", "Simmer for 15 minutes, stirring occasionally, until the vegetables are tender.", "Season with salt and pepper and serve hot."] },
  { id: "d11", slot: "dinner", style: "stir_fry", name: "Salmon Stir Fry", prepTime: 8, cookTime: 9,
    items: [{ food: "salmon", grams: 150 }, { food: "brown_rice", grams: 150 }, { food: "broccoli", grams: 100 }, { food: "bell_pepper", grams: 60 }, { food: "olive_oil", grams: 8 }, { food: "soy_sauce", grams: 12 }],
    instructions: ["Cube the salmon.", "Pan-sear in olive oil over medium heat until just cooked through, about 4-5 minutes, then set aside.", "Add the broccoli and bell pepper to the pan; stir-fry until tender-crisp, 4-5 minutes.", "Return the salmon to the pan with the soy sauce, tossing gently to combine and warm through, then serve over brown rice."] },
  { id: "d12", slot: "dinner", style: "salad", name: "Salmon & Avocado Salad", prepTime: 5, cookTime: 10,
    items: [{ food: "salmon", grams: 150 }, { food: "spinach", grams: 120 }, { food: "avocado", grams: 60 }, { food: "olive_oil", grams: 8 }],
    instructions: ["Season the salmon with salt and pepper.", "Pan-sear or bake until it flakes easily with a fork, about 8-10 minutes.", "Toss the spinach with olive oil in a bowl.", "Top with the salmon and sliced avocado."] },
  { id: "d13", slot: "dinner", style: "salad", name: "Tuna & Egg Salad", prepTime: 8, cookTime: 10,
    items: [{ food: "tuna", grams: 100 }, { food: "egg", grams: 100 }, { food: "spinach", grams: 100 }, { food: "olive_oil", grams: 8 }],
    instructions: ["Place the eggs in a pot of water and bring to a boil; boil about 10 minutes, then cool in cold water and peel.", "Drain the tuna and flake it into a bowl.", "Toss the spinach with olive oil.", "Slice the eggs and arrange over the spinach with the tuna."] },
  { id: "d14", slot: "dinner", style: "wrap_sandwich", name: "Chicken Caesar Wrap", prepTime: 5, cookTime: 10,
    items: [{ food: "chicken_breast", grams: 130 }, { food: "tortilla", grams: 60 }, { food: "parmesan_cheese", grams: 15 }, { food: "spinach", grams: 50 }, { food: "caesar_dressing", grams: 15 }],
    instructions: ["Season the chicken breast with salt and pepper.", "Pan-sear until cooked through, about 7-8 minutes, then slice.", "Warm the tortilla in a dry pan or microwave for 15-20 seconds.", "Toss the spinach with the Caesar dressing, then layer it with the chicken and shaved parmesan on the tortilla.", "Roll up tightly and slice in half."] },
  { id: "d15", slot: "dinner", style: "wrap_sandwich", name: "Beef & Cheese Wrap", prepTime: 5, cookTime: 8,
    items: [{ food: "ground_beef", grams: 120 }, { food: "tortilla", grams: 60 }, { food: "cheddar_cheese", grams: 25 }, { food: "bell_pepper", grams: 50 }],
    instructions: ["Brown the ground beef in a pan over medium heat, breaking it up as it cooks, about 6-7 minutes.", "Add the diced bell pepper in the last 2 minutes.", "Warm the tortilla in a dry pan or microwave for 15-20 seconds.", "Fill with the beef mixture, top with shredded cheddar, and roll up."] },
  { id: "d16", slot: "dinner", style: "stir_fry", name: "Chicken Stir Fry", prepTime: 8, cookTime: 9,
    items: [{ food: "chicken_breast", grams: 150 }, { food: "brown_rice", grams: 150 }, { food: "broccoli", grams: 100 }, { food: "bell_pepper", grams: 60 }, { food: "olive_oil", grams: 8 }, { food: "soy_sauce", grams: 12 }],
    instructions: ["Cut the chicken breast into thin strips.", "Stir-fry in olive oil over medium-high heat until cooked through, about 5 minutes.", "Add the broccoli and bell pepper; stir-fry until tender-crisp, 4-5 minutes.", "Stir in the soy sauce during the last minute, tossing to coat, then serve over brown rice."] },
  { id: "d17", slot: "dinner", style: "soup", name: "Chicken Tortilla Soup", prepTime: 5, cookTime: 15,
    items: [{ food: "chicken_breast", grams: 120 }, { food: "black_beans", grams: 100 }, { food: "bell_pepper", grams: 60 }, { food: "tortilla", grams: 40 }],
    instructions: ["Dice the chicken breast and cook in a pot over medium heat until browned, about 5 minutes.", "Add the black beans, diced bell pepper, and a splash of broth; simmer 10 minutes.", "Tear the tortilla into strips and stir in during the last 2 minutes to soften slightly.", "Season with salt and pepper and serve hot."] },
  { id: "d18", slot: "dinner", style: "bowl", name: "Baked Chicken & Broccoli", prepTime: 8, cookTime: 22,
    items: [{ food: "chicken_breast", grams: 150 }, { food: "broccoli", grams: 120 }, { food: "sweet_potato", grams: 150 }, { food: "olive_oil", grams: 5 }],
    instructions: ["Preheat the oven to 400°F.", "Cube the sweet potato, toss with olive oil, and spread on a baking sheet; roast 15 minutes.", "Add the seasoned chicken breast to the same sheet and roast another 15-18 minutes, until cooked through.", "Steam the broccoli in the last 5 minutes and plate everything together."] },

  // ---------- SNACK ----------
  { id: "s1", slot: "snack", prepTime: 2, cookTime: 0, name: "Apple & Almonds",
    items: [{ food: "apple", grams: 150 }, { food: "almonds", grams: 20 }],
    instructions: ["Slice the apple into wedges.", "Pair with a small handful of almonds."] },
  { id: "s2", slot: "snack", prepTime: 2, cookTime: 0, name: "Greek Yogurt Cup",
    items: [{ food: "greek_yogurt", grams: 150 }, { food: "blueberries", grams: 50 }],
    instructions: ["Spoon the yogurt into a cup or bowl.", "Top with blueberries and serve chilled."] },
  { id: "s3", slot: "snack", prepTime: 2, cookTime: 0, name: "Hummus & Carrots",
    items: [{ food: "hummus", grams: 60 }, { food: "carrots", grams: 100 }],
    instructions: ["Spoon the hummus into a small bowl.", "Serve with carrot sticks for dipping."] },
  { id: "s4", slot: "snack", prepTime: 1, cookTime: 0, name: "Trail Mix",
    items: [{ food: "trail_mix", grams: 40 }],
    instructions: ["Portion the trail mix into a small bowl or bag."] },
  { id: "s5", slot: "snack", prepTime: 3, cookTime: 0, name: "Cheese & Orange",
    items: [{ food: "cheddar_cheese", grams: 30 }, { food: "orange", grams: 130 }],
    instructions: ["Slice the cheese.", "Peel and segment the orange.", "Serve together."] },
  { id: "s6", slot: "snack", prepTime: 3, cookTime: 2, name: "PB & Banana Toast",
    items: [{ food: "whole_wheat_bread", grams: 35 }, { food: "peanut_butter", grams: 20 }, { food: "banana", grams: 100 }],
    instructions: ["Toast the bread until golden.", "Spread with peanut butter.", "Top with sliced banana."] },
  { id: "s7", slot: "snack", prepTime: 2, cookTime: 10, name: "Eggs & Apple",
    items: [{ food: "egg", grams: 100 }, { food: "apple", grams: 120 }],
    instructions: ["Place the eggs in a pot of water and bring to a boil.", "Boil for about 10 minutes, then transfer to cold water to cool.", "Peel and pair with sliced apple."] },
  { id: "s8", slot: "snack", prepTime: 2, cookTime: 0, name: "Cottage Cheese & Berries",
    items: [{ food: "cottage_cheese", grams: 150 }, { food: "blueberries", grams: 60 }],
    instructions: ["Spoon the cottage cheese into a bowl.", "Top with blueberries and serve chilled."] },
  { id: "s9", slot: "snack", prepTime: 3, cookTime: 0, name: "Turkey Roll-Ups",
    items: [{ food: "turkey_breast", grams: 80 }, { food: "cheddar_cheese", grams: 25 }],
    instructions: ["Lay out the turkey slices.", "Top each with a slice of cheddar and roll up."] },
  { id: "s10", slot: "snack", prepTime: 1, cookTime: 4, name: "Edamame Cup",
    items: [{ food: "edamame", grams: 150 }],
    instructions: ["Steam or microwave the edamame until hot, about 3-4 minutes.", "Sprinkle with a pinch of salt and serve in the pod or shelled."] },
  { id: "s11", slot: "snack", prepTime: 3, cookTime: 0, name: "Tuna & Veggie Sticks",
    items: [{ food: "tuna", grams: 80 }, { food: "carrots", grams: 100 }],
    instructions: ["Drain the tuna.", "Serve with carrot sticks for dipping or scooping."] },
  { id: "s12", slot: "snack", prepTime: 3, cookTime: 0, name: "Turkey & Apple Bites",
    items: [{ food: "turkey_breast", grams: 70 }, { food: "apple", grams: 120 }],
    instructions: ["Slice the apple into wedges.", "Pair with the sliced turkey breast."] },
  { id: "s13", slot: "snack", prepTime: 3, cookTime: 0, name: "Peanut Butter & Apple Slices",
    items: [{ food: "apple", grams: 150 }, { food: "peanut_butter", grams: 20 }],
    instructions: ["Slice the apple into wedges.", "Serve with peanut butter for dipping."] },
  { id: "s14", slot: "snack", prepTime: 2, cookTime: 0, name: "Protein Shake",
    items: [{ food: "protein_powder", grams: 30 }, { food: "almond_milk", grams: 250 }],
    instructions: ["Add the protein powder and almond milk to a shaker bottle or blender.", "Shake or blend until smooth.", "Serve immediately."] },
  { id: "s15", slot: "snack", prepTime: 1, cookTime: 0, name: "Protein Bar",
    items: [{ food: "protein_bar", grams: 60 }],
    instructions: ["Unwrap and enjoy."] },
  { id: "s16", slot: "snack", prepTime: 10, cookTime: 0, name: "Peanut Butter Protein Balls",
    items: [{ food: "oats", grams: 40 }, { food: "peanut_butter", grams: 30 }, { food: "protein_powder", grams: 20 }],
    instructions: ["Combine the oats, peanut butter, and protein powder in a bowl and mix until a thick dough forms (add a splash of almond milk if it's too dry).", "Roll into bite-sized balls.", "Chill in the fridge for at least 20 minutes to firm up before eating."] },
];
