// Each template: id, name, slot, style, items [{food, grams}], instructions (array of steps).
// Grams are BASE amounts for one serving before the planner scales them to hit calorie targets.
// style is a small preparation-format tag (reused across slots) used, alongside each item's
// proteinFamily in foods.js, to bias meal selection toward a person's stated preferences.
const MEAL_TEMPLATES = [
  // ---------- BREAKFAST ----------
  { id: "b1", slot: "breakfast", style: "oats", name: "Oatmeal with Banana & Peanut Butter",
    items: [{ food: "oats", grams: 60 }, { food: "almond_milk", grams: 200 }, { food: "banana", grams: 120 }, { food: "peanut_butter", grams: 16 }],
    instructions: ["Combine oats and almond milk in a pot, bring to a simmer for 4-5 minutes, stirring occasionally.", "Slice the banana and stir half in; top the bowl with the rest.", "Drizzle peanut butter on top and serve warm."] },
  { id: "b2", slot: "breakfast", style: "dairy_bowl", name: "Greek Yogurt Parfait",
    items: [{ food: "greek_yogurt", grams: 200 }, { food: "granola", grams: 40 }, { food: "blueberries", grams: 80 }],
    instructions: ["Layer yogurt, granola, and blueberries in a bowl or jar.", "Repeat layers once more if using a tall glass.", "Serve immediately so the granola stays crunchy."] },
  { id: "b3", slot: "breakfast", style: "eggs", name: "Veggie Egg Scramble with Toast",
    items: [{ food: "egg", grams: 150 }, { food: "spinach", grams: 40 }, { food: "bell_pepper", grams: 50 }, { food: "whole_wheat_bread", grams: 70 }],
    instructions: ["Whisk eggs and scramble in a lightly oiled pan over medium heat.", "Fold in chopped spinach and bell pepper during the last 2 minutes of cooking.", "Toast the bread and serve alongside."] },
  { id: "b4", slot: "breakfast", style: "eggs", name: "Avocado Toast with Egg",
    items: [{ food: "whole_wheat_bread", grams: 70 }, { food: "avocado", grams: 75 }, { food: "egg", grams: 50 }],
    instructions: ["Toast the bread until crisp.", "Mash the avocado with a pinch of salt and pepper, spread on top.", "Fry or poach the egg and place on top of the avocado."] },
  { id: "b5", slot: "breakfast", style: "dairy_bowl", name: "Cottage Cheese & Fruit Bowl",
    items: [{ food: "cottage_cheese", grams: 200 }, { food: "apple", grams: 120 }, { food: "almonds", grams: 15 }],
    instructions: ["Dice the apple.", "Combine cottage cheese, apple, and almonds in a bowl.", "Optional: add a dash of cinnamon."] },
  { id: "b6", slot: "breakfast", style: "eggs", name: "Eggs, Bacon & Toast",
    items: [{ food: "egg", grams: 120 }, { food: "bacon", grams: 40 }, { food: "whole_wheat_bread", grams: 70 }],
    instructions: ["Cook the bacon in a pan over medium heat until crisp; set aside on a paper towel.", "Fry or scramble the eggs in the leftover bacon fat (or a light oil).", "Toast the bread and serve everything together."] },
  { id: "b7", slot: "breakfast", style: "eggs", name: "Egg & Sausage Scramble with Toast",
    items: [{ food: "egg", grams: 120 }, { food: "breakfast_sausage", grams: 60 }, { food: "whole_wheat_bread", grams: 70 }, { food: "bell_pepper", grams: 40 }],
    instructions: ["Brown the breakfast sausage in a pan over medium heat, breaking it up as it cooks.", "Whisk in the eggs and diced bell pepper, scrambling until just set.", "Toast the bread and serve alongside."] },
  { id: "b8", slot: "breakfast", style: "eggs", name: "Breakfast Burrito",
    items: [{ food: "egg", grams: 120 }, { food: "cheddar_cheese", grams: 30 }, { food: "tortilla", grams: 60 }, { food: "bell_pepper", grams: 40 }],
    instructions: ["Scramble the eggs with the diced bell pepper in a lightly oiled pan.", "Warm the tortilla in a dry pan or microwave for 15-20 seconds.", "Fill with the scrambled eggs, top with shredded cheddar, and roll up."] },

  // ---------- LUNCH ----------
  { id: "l1", slot: "lunch", style: "bowl", name: "Chicken & Rice Bowl",
    items: [{ food: "chicken_breast", grams: 150 }, { food: "brown_rice", grams: 200 }, { food: "broccoli", grams: 100 }, { food: "olive_oil", grams: 5 }],
    instructions: ["Season and pan-sear or bake the chicken breast until cooked through (~165°F internal).", "Steam the broccoli for 4-5 minutes.", "Slice the chicken and serve over rice with broccoli, drizzled with olive oil."] },
  { id: "l2", slot: "lunch", style: "wrap_sandwich", name: "Turkey & Hummus Wrap Plate",
    items: [{ food: "turkey_breast", grams: 100 }, { food: "whole_wheat_bread", grams: 70 }, { food: "hummus", grams: 40 }, { food: "carrots", grams: 60 }],
    instructions: ["Spread hummus on the bread.", "Layer sliced turkey breast on top and fold or roll.", "Serve with carrot sticks on the side."] },
  { id: "l3", slot: "lunch", style: "salad", name: "Quinoa Black Bean Salad",
    items: [{ food: "quinoa", grams: 150 }, { food: "black_beans", grams: 120 }, { food: "bell_pepper", grams: 60 }, { food: "avocado", grams: 50 }, { food: "olive_oil", grams: 5 }],
    instructions: ["Combine cooked quinoa, black beans, and diced bell pepper in a bowl.", "Top with sliced avocado.", "Drizzle with olive oil and a squeeze of lime if available; toss and serve."] },
  { id: "l4", slot: "lunch", style: "stir_fry", name: "Tofu Veggie Stir Fry",
    items: [{ food: "tofu", grams: 150 }, { food: "brown_rice", grams: 150 }, { food: "broccoli", grams: 100 }, { food: "bell_pepper", grams: 60 }, { food: "olive_oil", grams: 8 }],
    instructions: ["Press tofu, cube it, and pan-fry in olive oil until golden.", "Add broccoli and bell pepper, stir-fry 4-5 minutes until tender-crisp.", "Serve over brown rice with soy sauce to taste."] },
  { id: "l5", slot: "lunch", style: "soup", name: "Lentil Soup with Bread",
    items: [{ food: "lentils", grams: 250 }, { food: "carrots", grams: 60 }, { food: "whole_wheat_bread", grams: 50 }],
    instructions: ["Simmer cooked lentils with diced carrots and a splash of broth for 10 minutes.", "Season with cumin, salt, and pepper.", "Serve hot with a side of bread."] },
  { id: "l6", slot: "lunch", style: "bowl", name: "Salmon Spinach Quinoa Bowl",
    items: [{ food: "salmon", grams: 120 }, { food: "spinach", grams: 60 }, { food: "quinoa", grams: 100 }, { food: "olive_oil", grams: 5 }],
    instructions: ["Pan-sear or bake the salmon until it flakes easily.", "Wilt spinach lightly in a warm pan.", "Serve salmon over quinoa and spinach, drizzled with olive oil."] },
  { id: "l7", slot: "lunch", style: "wrap_sandwich", name: "Turkey & Cheese Sandwich",
    items: [{ food: "turkey_breast", grams: 90 }, { food: "whole_wheat_bread", grams: 70 }, { food: "cheddar_cheese", grams: 25 }, { food: "carrots", grams: 60 }],
    instructions: ["Layer the sliced turkey and cheddar between the bread.", "Cut in half.", "Serve with carrot sticks on the side."] },
  { id: "l8", slot: "lunch", style: "wrap_sandwich", name: "Grilled Cheese & Apple",
    items: [{ food: "whole_wheat_bread", grams: 70 }, { food: "cheddar_cheese", grams: 40 }, { food: "olive_oil", grams: 5 }, { food: "apple", grams: 120 }],
    instructions: ["Layer the cheddar between the bread slices.", "Pan-fry in the olive oil over medium heat, a few minutes per side, until golden and the cheese melts.", "Serve with sliced apple on the side."] },

  // ---------- DINNER ----------
  { id: "d1", slot: "dinner", style: "bowl", name: "Baked Salmon with Sweet Potato",
    items: [{ food: "salmon", grams: 150 }, { food: "sweet_potato", grams: 200 }, { food: "broccoli", grams: 100 }, { food: "olive_oil", grams: 5 }],
    instructions: ["Bake the sweet potato (cubed) at 400°F for 20-25 minutes, tossed in olive oil.", "Bake or pan-sear the salmon for the last 12-15 minutes.", "Steam broccoli and plate everything together."] },
  { id: "d2", slot: "dinner", style: "stir_fry", name: "Lean Beef & Veggie Stir Fry",
    items: [{ food: "ground_beef", grams: 120 }, { food: "brown_rice", grams: 180 }, { food: "bell_pepper", grams: 80 }, { food: "broccoli", grams: 80 }],
    instructions: ["Brown the ground beef in a pan, breaking it up, until fully cooked.", "Add bell pepper and broccoli, stir-fry 5 minutes.", "Serve over brown rice."] },
  { id: "d3", slot: "dinner", style: "bowl", name: "Chicken Fajita Bowl",
    items: [{ food: "chicken_breast", grams: 150 }, { food: "bell_pepper", grams: 100 }, { food: "brown_rice", grams: 150 }, { food: "cheddar_cheese", grams: 20 }],
    instructions: ["Slice chicken and bell peppers into strips; season with fajita spices.", "Sauté together over medium-high heat until chicken is cooked through.", "Serve over rice topped with shredded cheddar."] },
  { id: "d4", slot: "dinner", style: "soup", name: "Turkey & Black Bean Chili",
    items: [{ food: "turkey_breast", grams: 120 }, { food: "black_beans", grams: 150 }, { food: "bell_pepper", grams: 60 }, { food: "cheddar_cheese", grams: 20 }],
    instructions: ["Cook diced or ground turkey in a pot until browned.", "Add black beans, bell pepper, and chili spices; simmer 15 minutes.", "Top with shredded cheddar before serving."] },
  { id: "d5", slot: "dinner", style: "bowl", name: "Pasta with Tofu & Spinach",
    items: [{ food: "pasta", grams: 200 }, { food: "tofu", grams: 120 }, { food: "spinach", grams: 60 }, { food: "olive_oil", grams: 8 }],
    instructions: ["Cook pasta according to package instructions.", "Pan-fry cubed tofu in olive oil until golden; wilt in spinach at the end.", "Toss tofu and spinach through the pasta."] },
  { id: "d6", slot: "dinner", style: "bowl", name: "Sweet Potato & Black Bean Bowl",
    items: [{ food: "sweet_potato", grams: 200 }, { food: "black_beans", grams: 150 }, { food: "spinach", grams: 40 }, { food: "avocado", grams: 50 }],
    instructions: ["Roast cubed sweet potato at 400°F for 20-25 minutes.", "Warm the black beans with a pinch of cumin.", "Assemble in a bowl over spinach, topped with sliced avocado."] },
  { id: "d7", slot: "dinner", style: "bowl", name: "Chicken & Broccoli Pasta",
    items: [{ food: "pasta", grams: 200 }, { food: "chicken_breast", grams: 130 }, { food: "broccoli", grams: 100 }, { food: "olive_oil", grams: 8 }],
    instructions: ["Cook pasta according to package instructions.", "Pan-sear the chicken until cooked through, then slice.", "Steam the broccoli, then toss everything together with the pasta and olive oil."] },

  // ---------- SNACK ----------
  { id: "s1", slot: "snack", name: "Apple & Almonds",
    items: [{ food: "apple", grams: 150 }, { food: "almonds", grams: 20 }],
    instructions: ["Slice the apple and pair with a small handful of almonds."] },
  { id: "s2", slot: "snack", name: "Greek Yogurt Cup",
    items: [{ food: "greek_yogurt", grams: 150 }, { food: "blueberries", grams: 50 }],
    instructions: ["Top yogurt with blueberries and serve chilled."] },
  { id: "s3", slot: "snack", name: "Hummus & Carrots",
    items: [{ food: "hummus", grams: 60 }, { food: "carrots", grams: 100 }],
    instructions: ["Serve hummus with carrot sticks for dipping."] },
  { id: "s4", slot: "snack", name: "Trail Mix",
    items: [{ food: "trail_mix", grams: 40 }],
    instructions: ["Portion trail mix into a small bowl or bag."] },
  { id: "s5", slot: "snack", name: "Cheese & Orange",
    items: [{ food: "cheddar_cheese", grams: 30 }, { food: "orange", grams: 130 }],
    instructions: ["Pair sliced cheese with a fresh orange."] },
  { id: "s6", slot: "snack", name: "PB & Banana Toast",
    items: [{ food: "whole_wheat_bread", grams: 35 }, { food: "peanut_butter", grams: 20 }, { food: "banana", grams: 100 }],
    instructions: ["Toast the bread.", "Spread with peanut butter.", "Top with sliced banana."] },
];
